[project]
name = "repl-nix-replitbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "psycopg2-binary>=2.9.10",
    "telegram>=0.0.1",
]
